// Css
import "./globals.css"
// Fonts
import { fontMono, fontSans } from "./fonts"
// Meta Data
export const metadata = {
  title: "Book Marketing",
  description: "Generated by Book Marketing",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    }
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased font-sans font-normal text-black`}>
        <amin>
          {children}
        </amin>
      </body>
    </html>
  )
}